### ISSUE TITLE
unable to use ngAnimate

### ISSUE THREAD

**Issue by ip-amity-tarun** [sotospez/sotos.angular-slider#2]
I have added the ngAnimate dependency and angular-animate.min.js(v-1.4) as well but the classes on the slider DOM element are not added or removed by the ngAnimate. please help me to enable animation on your module. 
Thanks!
Tarun

**Comment by sotospez** [comment]
ngAnimate require on angular-slider
//in the module 
var sotosAngularSlider=angular.module("sotos.angular-slider",["ngAnimate","sotos.tmp"])

in your js 
var app = angular.module('app', ['ngAnimate','sotos.angular-slider','ngSanitize']);
check the demo files if helps you 
thanks

**Comment by jamesbyrneiitd** [comment]
We have already added this in both the module as well as our js file but nothing is happening!

We are at lost and even replaced the ng-animate js file but of no help either. Is there anything else we are missing out?

It would be a great help if you could kindly zip the working demo.

**Comment by sotospez** [comment]
check full source
