### ISSUE TITLE
Slider not working on Angular Scaffolding

### ISSUE THREAD

**Issue by dannygoncalves** [sotospez/sotos.angular-slider#3]
I'm having an issue trying to use your component.

After i do:

bower install sotos.angular-slider --save (in order to add it to my bower.json)

and adding to the module 'sotos.angular-slider'

I get the following error: 

Uncaught Error: [$injector:modulerr] Failed to instantiate module gulpAngular due to:
Error: [$injector:modulerr] Failed to instantiate module sotos.angular-slider due to:
Error: [$injector:nomod] Module 'sotos.angular-slider' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

When i inspect the source in the bower components folder i see some differences between sotos.angular-slider and sotos-angular-slider, any approach or advise in here?

I really like the slider but i'm not being able to use it.

**Comment by sotospez** [comment]
hi
I fix the name of the module also i change the name of files 
sotos.angular-slider.min.css
sotos.angular-slider.min.js 
thanks
